### ISSUE TITLE
Multi snap

### ISSUE THREAD

**Issue by Julianfrom515** [suryadip2008/SE-Scripts#2]
On the new version of Snapchat there's a feature called multisnap where you can snap up to 20 pictures and send them all at once just for a snap score
![Screenshot_20241117_200424_Google](https://github.com/user-attachments/assets/357565a4-4706-4198-adc0-6d513cf183ce)

**Comment by suryadip2008** [comment]
> On the new version of Snapchat there's a feature called multisnap where you can snap up to 20 pictures and send them all at once just for a snap score ![Screenshot_20241117_200424_Google](https://private-user-images.githubusercontent.com/188811240/387030062-357565a4-4706-4198-adc0-6d513cf183ce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDk3OTQsIm5iZiI6MTczMTk0OTQ5NCwicGF0aCI6Ii8xODg4MTEyNDAvMzg3MDMwMDYyLTM1NzU2NWE0LTQ3MDYtNDE5OC1hZGMwLTZkNTEzY2YxODNjZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxNzA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWVjNTE5YzFhNzFjODY2MDI5MDFkMDAxZWU3M2Y2YjJkNWRhYzZhN2MwZmIxMjk0MjRhY2JiY2VmNDNlNmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iHGfFLYm2nEQWfOl6_06_hVKvtprakPNj-fB58nfTpY)

Hello!! Thank you for opening a script request in the SE-Scripts repo!! Unfortunately, the feature that you are requesting is not possible as a script rather it can be made possible by tweaking the Snapchat app through Snapenhance itself (which is highly unlikely though as older versions of Snapchat do not have that Multi Snap Feature).

Multi Snap Feature is a server sided feature and can be only implemented by the Snapchat developers themselves and cannot be implemented by tweaking the existing app. If you really plan to use, Multi Snap Feature, I'm afraid you would have to update to the latest version of Snapchat which would put your account at risk due to the detections implemented by Snapchat. So please wait for any Bypass released by Snapenhance developers till you use the latest version of Snapchat or do not use Snapenhance if you really want Multi Snap Feature.
